name: lokalise_flutter_sdk
description: Lokalise Flutter SDK over-the-air translations updates. This package provides new translations from lokalise.com without a new app release.
version: 0.2.2
homepage: https://github.com/lokalise/lokalise-flutter-sdk

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dart_style: ^2.2.3
  flutter:
    sdk: flutter
  intl: ^0.17.0
  path: ^1.8.0
  petitparser: ">=4.0.0 <6.0.0"
  analyzer: ">=3.0.0 <5.0.0"
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  archive: ^3.3.1
  path_provider: ^2.0.11
  package_info_plus: ^1.4.3+1
  universal_io: ^2.0.4
  
dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.0

executables:
  tr:  

platforms:
  ios:
  android:
  macos:
  windows:   
  linux:
  web: